name: Test Workflow

on:
  push:
    branches: [ "main" ]   # or whichever branch we use

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple check
        run: echo "workflows success!"

